### PR TITLE
agp 3.5.1

### LINKED ISSUE #48: SpoonPlugin.kt - Two deprecation warnings with Android Gradle Plugin 3.3
Now is build with Android Studio 3.3 successful, but deprecation warning is displayed:

1. variant.getAssemble()

`13:54:28.610 [WARN] [org.gradle.api.Project] WARNING: API 'variant.getAssemble()' is obsolete and has been replaced with 'variant.getAssembleProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
REASON: It is currently called from the following trace:
java.lang.Thread.getStackTrace(Thread.java:1559)
com.android.build.gradle.internal.errors.DeprecationReporterImpl.reportDeprecatedApi(DeprecationReporterImpl.kt:79)
com.android.build.gradle.internal.api.BaseVariantImpl.getAssemble(BaseVariantImpl.java:571)
com.android.build.gradle.internal.api.ApplicationVariantImpl_Decorated.getAssemble(null:-1)
com.jaredsburrows.spoon.SpoonPlugin$configureAndroidProject$1$1.execute(SpoonPlugin.kt:41)
com.jaredsburrows.spoon.SpoonPlugin$configureAndroidProject$1$1.execute(SpoonPlugin.kt:12)
...
...`

2. variantOutput.getPackageApplication()

`13:54:28.614 [WARN] [org.gradle.api.Project] WARNING: API 'variantOutput.getPackageApplication()' is obsolete and has been replaced with 'variant.getPackageApplicationProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
REASON: It is currently called from the following trace:
java.lang.Thread.getStackTrace(Thread.java:1559)
com.android.build.gradle.internal.errors.DeprecationReporterImpl.reportDeprecatedApi(DeprecationReporterImpl.kt:79)
com.android.build.gradle.internal.api.ApkVariantOutputImpl.getPackageApplication(ApkVariantOutputImpl.java:57)
com.android.build.gradle.internal.api.ApkVariantOutputImpl_Decorated.getPackageApplication(null:-1)
com.android.build.gradle.internal.api.ApkVariantOutputImpl.getOutputFile(ApkVariantOutputImpl.java:68)
com.android.build.gradle.internal.api.ApkVariantOutputImpl_Decorated.getOutputFile(null:-1)
com.jaredsburrows.spoon.SpoonPlugin$configureAndroidProject$1$1.execute(SpoonPlugin.kt:42)
com.jaredsburrows.spoon.SpoonPlugin$configureAndroidProject$1$1.execute(SpoonPlugin.kt:12)
...
...`

Thanks.

### PR DESCRIPTION
**Pull request by jaredsburrows**
Closes #48
Closes #68

### CODE REVIEW

File: src/main/kotlin/com/jaredsburrows/spoon/SpoonPlugin.kt [hunk 1]
```diff
@@ -34,7 +34,16 @@ class SpoonPlugin : Plugin<Project> {
           description = "Run instrumentation tests for '${variant.name}' variant."
           group = "Verification"
           outputs.upToDateWhen { false }
-          dependsOn(variant.testedVariant.assemble, variant.assemble)
+          variant.testedVariant.assembleProvider.configure { provider ->
```
Comment (pjakubczyk) [inline src/main/kotlin/com/jaredsburrows/spoon/SpoonPlugin.kt]: I guess we can just stick to 
https://github.com/jaredsburrows/gradle-spoon-plugin/pull/68/files#diff-8ced7b9d1d36deac751b5d9ddc0ce435R37
my PR is almost ready apart from fact that it passes locally not on TravisCI :/

**Comment by pjakubczyk** [comment]
https://github.com/jaredsburrows/gradle-spoon-plugin/pull/73
